"""
database/models.py
All database table definitions using SQLAlchemy ORM.
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, Boolean,
    DateTime, Text, JSON, ForeignKey, Index
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


class Candle(Base):
    """OHLCV candle data for every pair, exchange, and timeframe."""
    __tablename__ = "candles"

    id          = Column(Integer, primary_key=True)
    exchange    = Column(String(20), nullable=False)
    pair        = Column(String(20), nullable=False)
    timeframe   = Column(String(5),  nullable=False)
    timestamp   = Column(DateTime,   nullable=False)
    open        = Column(Float,      nullable=False)
    high        = Column(Float,      nullable=False)
    low         = Column(Float,      nullable=False)
    close       = Column(Float,      nullable=False)
    volume      = Column(Float,      nullable=False)
    num_trades  = Column(Integer)

    # Pre-computed indicators (stored to avoid re-calculation)
    rsi         = Column(Float)
    macd        = Column(Float)
    macd_signal = Column(Float)
    macd_hist   = Column(Float)
    bb_upper    = Column(Float)
    bb_mid      = Column(Float)
    bb_lower    = Column(Float)
    ema_fast    = Column(Float)
    ema_slow    = Column(Float)
    volume_sma  = Column(Float)  # 20-period volume SMA

    created_at  = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_candles_lookup", "exchange", "pair", "timeframe", "timestamp"),
    )


class Signal(Base):
    """Every signal generated by the signal engine, pass or fail."""
    __tablename__ = "signals"

    id                = Column(Integer, primary_key=True)
    timestamp         = Column(DateTime, nullable=False, default=datetime.utcnow)
    pair              = Column(String(20), nullable=False)
    exchange          = Column(String(20))          # Primary exchange
    exchange_b        = Column(String(20))          # For arb: second exchange
    signal_type       = Column(String(20), nullable=False)  # arb | momentum | reversion
    direction         = Column(String(5))           # long | short | arb
    score             = Column(Float, nullable=False)
    passed_gate       = Column(Boolean, default=False)

    # Indicator snapshot at signal time
    rsi               = Column(Float)
    macd_hist         = Column(Float)
    bb_position       = Column(Float)   # 0=lower band, 1=upper band
    volume_ratio      = Column(Float)   # vs 20-period avg
    arb_gap_pct       = Column(Float)   # For arb signals

    # Sentiment context
    sentiment_score   = Column(Float)
    sentiment_mod     = Column(Float)   # +/- applied to score
    sentiment_velocity = Column(Float)

    # Timeframe confirmation
    tf_5m_confirm     = Column(Boolean)
    tf_15m_confirm    = Column(Boolean)
    tf_1h_confirm     = Column(Boolean)

    # Full indicator snapshot as JSON (for ML features later)
    indicators_json   = Column(JSON)

    # Claude analysis
    claude_reasoning  = Column(Text)
    claude_suggested_entry  = Column(Float)
    claude_suggested_sl     = Column(Float)
    claude_suggested_tp     = Column(Float)
    claude_suggested_size   = Column(Float)
    claude_risk_reward      = Column(Float)
    claude_api_cost_usd     = Column(Float)

    # User decision
    user_action       = Column(String(10))  # go | skip | modify | expired
    user_action_at    = Column(DateTime)
    skip_reason       = Column(Text)        # Why the signal was not acted on (free text)

    # Price evolution after the signal — written by the bot's future-price
    # tracker loop so we can later evaluate whether passing/skipping was correct.
    price_at_signal   = Column(Float)
    price_1h          = Column(Float)
    price_4h          = Column(Float)
    price_24h         = Column(Float)

    # Outcome (filled when trade closes)
    outcome           = Column(String(10))  # win | loss | breakeven | open
    outcome_pnl_pct   = Column(Float)

    # Profile and strategy active at time of signal
    profile           = Column(String(30))
    strategy          = Column(String(30))

    # Relationships
    trade             = relationship("Trade", back_populates="signal", uselist=False)
    prediction        = relationship("Prediction", back_populates="signal", uselist=False)

    __table_args__ = (
        Index("ix_signals_timestamp", "timestamp"),
        Index("ix_signals_pair", "pair"),
        Index("ix_signals_type", "signal_type"),
    )


class Trade(Base):
    """Executed trades — both sim and live."""
    __tablename__ = "trades"

    id              = Column(Integer, primary_key=True)
    signal_id       = Column(Integer, ForeignKey("signals.id"))
    timestamp_open  = Column(DateTime, nullable=False, default=datetime.utcnow)
    timestamp_close = Column(DateTime)

    pair            = Column(String(20), nullable=False)
    exchange        = Column(String(20), nullable=False)
    exchange_b      = Column(String(20))   # For arb: closing exchange
    side            = Column(String(5),  nullable=False)  # long | short | arb
    signal_type     = Column(String(20))

    entry_price     = Column(Float, nullable=False)
    exit_price      = Column(Float)
    size_usd        = Column(Float, nullable=False)
    size_base       = Column(Float)    # Amount in base currency

    stop_loss       = Column(Float)
    take_profit     = Column(Float)

    fees_usd        = Column(Float, default=0.0)
    pnl_usd         = Column(Float)
    pnl_pct         = Column(Float)
    hold_minutes    = Column(Float)

    exit_reason     = Column(String(20))  # tp_hit | sl_hit | manual | kill_switch

    # Claude's post-trade review (written by the bot's self-review loop)
    claude_postmortem = Column(Text)

    sim_mode        = Column(Boolean, nullable=False, default=True)
    profile         = Column(String(30))
    strategy        = Column(String(30))

    # Exchange order IDs (None in sim mode)
    order_id_open   = Column(String(80))
    order_id_close  = Column(String(80))

    signal          = relationship("Signal", back_populates="trade")

    __table_args__ = (
        Index("ix_trades_timestamp", "timestamp_open"),
        Index("ix_trades_pair", "pair"),
    )


class SentimentSnapshot(Base):
    """Sentiment scores per coin, captured every 5 minutes."""
    __tablename__ = "sentiment"

    id              = Column(Integer, primary_key=True)
    timestamp       = Column(DateTime, nullable=False, default=datetime.utcnow)
    coin            = Column(String(10), nullable=False)  # BTC | ETH | SOL | MARKET

    reddit_score    = Column(Float)
    telegram_score  = Column(Float)
    news_score      = Column(Float)
    fear_greed      = Column(Float)
    google_trends   = Column(Float)

    composite       = Column(Float)    # Weighted blend
    velocity        = Column(Float)    # Change vs 2h ago

    post_count      = Column(Integer)  # Reddit posts analysed
    mention_count   = Column(Integer)  # Total mentions across sources

    __table_args__ = (
        Index("ix_sentiment_lookup", "coin", "timestamp"),
    )


class SentimentLog(Base):
    """Per-source sentiment readings from the pluggable aggregator.

    Every call to a source's fetch() yields one row, regardless of whether
    it contributed to the composite. The composite_score column stores the
    aggregator's blended value at the time this source was logged so the
    composite history is queryable from any single row.
    """
    __tablename__ = "sentiment_log"

    id              = Column(Integer, primary_key=True)
    timestamp       = Column(DateTime, nullable=False, default=datetime.utcnow)
    source_id       = Column(String(30), nullable=False)
    score           = Column(Float)            # -100..+100 per source
    composite_score = Column(Float)            # Aggregator output at log time
    hard_block      = Column(Boolean, default=False)
    block_reason    = Column(Text)
    confidence      = Column(Float)            # 0–1, weights composite
    raw_data        = Column(JSON)             # Source-specific payload

    __table_args__ = (
        Index("ix_sentiment_log_lookup", "source_id", "timestamp"),
    )


class DataLog(Base):
    """Every DataPoint observed by data_sources/.

    One row per (source_id, metric, symbol, timestamp). Same pattern as
    SentimentLog — every fetch is preserved so retrospective analysis
    can ask "what was VIX when this trade opened?" without needing to
    replay external APIs.
    """
    __tablename__ = "data_log"

    id        = Column(Integer, primary_key=True)
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)
    source_id = Column(String(30), nullable=False)
    metric    = Column(String(40), nullable=False)
    symbol    = Column(String(20))           # nullable — global metrics omit it
    value     = Column(Float)
    raw_data  = Column(JSON)
    error     = Column(Text)

    __table_args__ = (
        Index("ix_data_log_lookup", "source_id", "metric", "symbol", "timestamp"),
    )


class Prediction(Base):
    """Predictive model outputs per signal (phase 2 feature)."""
    __tablename__ = "predictions"

    id              = Column(Integer, primary_key=True)
    signal_id       = Column(Integer, ForeignKey("signals.id"))
    timestamp       = Column(DateTime, default=datetime.utcnow)

    model_version   = Column(String(20))
    win_probability = Column(Float)     # 0.0 – 1.0
    expected_pnl_pct = Column(Float)
    confidence      = Column(Float)

    # Feature vector used (JSON for auditability)
    features_json   = Column(JSON)

    # Was the prediction correct?
    correct         = Column(Boolean)   # Filled when trade closes

    signal          = relationship("Signal", back_populates="prediction")


class DailyStats(Base):
    """Aggregated daily performance — written at end of each day."""
    __tablename__ = "daily_stats"

    id                  = Column(Integer, primary_key=True)
    date                = Column(String(10), nullable=False, unique=True)  # YYYY-MM-DD

    total_signals       = Column(Integer, default=0)
    signals_passed_gate = Column(Integer, default=0)
    signals_acted_on    = Column(Integer, default=0)

    total_trades        = Column(Integer, default=0)
    wins                = Column(Integer, default=0)
    losses              = Column(Integer, default=0)
    win_rate            = Column(Float)

    pnl_usd             = Column(Float, default=0.0)
    pnl_pct             = Column(Float, default=0.0)
    fees_usd            = Column(Float, default=0.0)

    best_trade_pnl_pct  = Column(Float)
    worst_trade_pnl_pct = Column(Float)
    avg_hold_minutes    = Column(Float)

    best_signal_type    = Column(String(20))
    avg_score_winners   = Column(Float)
    avg_score_losers    = Column(Float)

    portfolio_value_usd = Column(Float)
    portfolio_peak_usd  = Column(Float)

    claude_api_cost_usd = Column(Float, default=0.0)
    sim_mode            = Column(Boolean, default=True)
    profile             = Column(String(30))
    strategy            = Column(String(30))


class ArbTrade(Base):
    """One row per arb attempt by execution/arb_engine.py.

    Logged whether or not the trade succeeded; the `success` flag and
    `error` field tell them apart. P&L columns are USD because arb is
    flat-quoted in USD-equivalent across exchanges.
    """
    __tablename__ = "arb_trades"

    id             = Column(Integer, primary_key=True)
    timestamp      = Column(DateTime, default=datetime.utcnow)
    symbol         = Column(String(20), nullable=False)
    buy_exchange   = Column(String(20))
    sell_exchange  = Column(String(20))
    buy_price      = Column(Float)
    sell_price     = Column(Float)
    buy_fill       = Column(Float)
    sell_fill      = Column(Float)
    gross_gap_pct  = Column(Float)
    net_gap_pct    = Column(Float)
    size_usd       = Column(Float)
    gross_pnl_usd  = Column(Float)
    net_pnl_usd    = Column(Float)
    execution_ms   = Column(Float)
    sim_mode       = Column(Boolean, default=True)
    success        = Column(Boolean, default=False)
    error          = Column(Text)

    __table_args__ = (
        Index("ix_arb_trades_lookup", "symbol", "timestamp"),
    )


class PortfolioSnapshot(Base):
    """Aggregated cross-agent state captured every PORTFOLIO_MONITOR_INTERVAL_SEC.

    snapshot_json carries the full stats dict so the analysis dashboard
    can reconstruct any past portfolio state without joining tables.
    """
    __tablename__ = "portfolio_snapshots"

    id                 = Column(Integer, primary_key=True)
    timestamp          = Column(DateTime, nullable=False, default=datetime.utcnow)
    total_equity       = Column(Float)
    total_daily_pnl    = Column(Float)
    total_exposure_pct = Column(Float)
    agents_running     = Column(Integer)
    portfolio_status   = Column(String(20))  # HEALTHY | WARNING | HALTED
    snapshot_json      = Column(JSON)

    __table_args__ = (
        Index("ix_portfolio_snapshots_ts", "timestamp"),
    )


class AgentEvent(Base):
    """Lifecycle event log per agent (STARTED, STOPPED, HALTED, KILLED, ERROR)."""
    __tablename__ = "agent_events"

    id         = Column(Integer, primary_key=True)
    timestamp  = Column(DateTime, default=datetime.utcnow)
    agent_id   = Column(String(30), nullable=False)
    event_type = Column(String(20))      # STARTED | STOPPED | HALTED | KILLED | ERROR | SKIPPED
    detail     = Column(Text)

    __table_args__ = (
        Index("ix_agent_events_lookup", "agent_id", "timestamp"),
    )


class CircuitBreakerLog(Base):
    """Log every time a circuit breaker fires."""
    __tablename__ = "circuit_breaker_log"

    id          = Column(Integer, primary_key=True)
    timestamp   = Column(DateTime, default=datetime.utcnow)
    reason      = Column(String(50))   # daily_loss | consecutive_loss | drawdown | kill_switch
    detail      = Column(Text)
    auto_resume_at = Column(DateTime)  # When bot will auto-resume (if applicable)
    manually_resolved = Column(Boolean, default=False)
