"""
database/models.py
All database table definitions using SQLAlchemy ORM.
"""

from datetime import datetime
from sqlalchemy import (
    Column, Integer, Float, String, Boolean,
    DateTime, Text, JSON, ForeignKey, Index
)
from sqlalchemy.orm import DeclarativeBase, relationship


class Base(DeclarativeBase):
    pass


class Candle(Base):
    """OHLCV candle data for every pair, exchange, and timeframe."""
    __tablename__ = "candles"

    id          = Column(Integer, primary_key=True)
    exchange    = Column(String(20), nullable=False)
    pair        = Column(String(20), nullable=False)
    timeframe   = Column(String(5),  nullable=False)
    timestamp   = Column(DateTime,   nullable=False)
    open        = Column(Float,      nullable=False)
    high        = Column(Float,      nullable=False)
    low         = Column(Float,      nullable=False)
    close       = Column(Float,      nullable=False)
    volume      = Column(Float,      nullable=False)
    num_trades  = Column(Integer)

    # Pre-computed indicators (stored to avoid re-calculation)
    rsi         = Column(Float)
    macd        = Column(Float)
    macd_signal = Column(Float)
    macd_hist   = Column(Float)
    bb_upper    = Column(Float)
    bb_mid      = Column(Float)
    bb_lower    = Column(Float)
    ema_fast    = Column(Float)
    ema_slow    = Column(Float)
    volume_sma  = Column(Float)  # 20-period volume SMA

    created_at  = Column(DateTime, default=datetime.utcnow)

    __table_args__ = (
        Index("ix_candles_lookup", "exchange", "pair", "timeframe", "timestamp"),
    )


class Signal(Base):
    """Every signal generated by the signal engine, pass or fail."""
    __tablename__ = "signals"

    id                = Column(Integer, primary_key=True)
    timestamp         = Column(DateTime, nullable=False, default=datetime.utcnow)
    pair              = Column(String(20), nullable=False)
    exchange          = Column(String(20))          # Primary exchange
    exchange_b        = Column(String(20))          # For arb: second exchange
    signal_type       = Column(String(20), nullable=False)  # arb | momentum | reversion
    direction         = Column(String(5))           # long | short | arb
    score             = Column(Float, nullable=False)
    passed_gate       = Column(Boolean, default=False)

    # Indicator snapshot at signal time
    rsi               = Column(Float)
    macd_hist         = Column(Float)
    bb_position       = Column(Float)   # 0=lower band, 1=upper band
    volume_ratio      = Column(Float)   # vs 20-period avg
    arb_gap_pct       = Column(Float)   # For arb signals

    # Sentiment context
    sentiment_score   = Column(Float)
    sentiment_mod     = Column(Float)   # +/- applied to score
    sentiment_velocity = Column(Float)

    # Timeframe confirmation
    tf_5m_confirm     = Column(Boolean)
    tf_15m_confirm    = Column(Boolean)
    tf_1h_confirm     = Column(Boolean)

    # Full indicator snapshot as JSON (for ML features later)
    indicators_json   = Column(JSON)

    # Claude analysis
    claude_reasoning  = Column(Text)
    claude_suggested_entry  = Column(Float)
    claude_suggested_sl     = Column(Float)
    claude_suggested_tp     = Column(Float)
    claude_suggested_size   = Column(Float)
    claude_risk_reward      = Column(Float)
    claude_api_cost_usd     = Column(Float)

    # User decision
    user_action       = Column(String(10))  # go | skip | modify | expired
    user_action_at    = Column(DateTime)

    # Outcome (filled when trade closes)
    outcome           = Column(String(10))  # win | loss | breakeven | open
    outcome_pnl_pct   = Column(Float)

    # Profile and strategy active at time of signal
    profile           = Column(String(30))
    strategy          = Column(String(30))

    # Relationships
    trade             = relationship("Trade", back_populates="signal", uselist=False)
    prediction        = relationship("Prediction", back_populates="signal", uselist=False)

    __table_args__ = (
        Index("ix_signals_timestamp", "timestamp"),
        Index("ix_signals_pair", "pair"),
        Index("ix_signals_type", "signal_type"),
    )


class Trade(Base):
    """Executed trades — both sim and live."""
    __tablename__ = "trades"

    id              = Column(Integer, primary_key=True)
    signal_id       = Column(Integer, ForeignKey("signals.id"))
    timestamp_open  = Column(DateTime, nullable=False, default=datetime.utcnow)
    timestamp_close = Column(DateTime)

    pair            = Column(String(20), nullable=False)
    exchange        = Column(String(20), nullable=False)
    exchange_b      = Column(String(20))   # For arb: closing exchange
    side            = Column(String(5),  nullable=False)  # long | short | arb
    signal_type     = Column(String(20))

    entry_price     = Column(Float, nullable=False)
    exit_price      = Column(Float)
    size_usd        = Column(Float, nullable=False)
    size_base       = Column(Float)    # Amount in base currency

    stop_loss       = Column(Float)
    take_profit     = Column(Float)

    fees_usd        = Column(Float, default=0.0)
    pnl_usd         = Column(Float)
    pnl_pct         = Column(Float)
    hold_minutes    = Column(Float)

    exit_reason     = Column(String(20))  # tp_hit | sl_hit | manual | kill_switch

    sim_mode        = Column(Boolean, nullable=False, default=True)
    profile         = Column(String(30))
    strategy        = Column(String(30))

    # Exchange order IDs (None in sim mode)
    order_id_open   = Column(String(80))
    order_id_close  = Column(String(80))

    signal          = relationship("Signal", back_populates="trade")

    __table_args__ = (
        Index("ix_trades_timestamp", "timestamp_open"),
        Index("ix_trades_pair", "pair"),
    )


class SentimentSnapshot(Base):
    """Sentiment scores per coin, captured every 5 minutes."""
    __tablename__ = "sentiment"

    id              = Column(Integer, primary_key=True)
    timestamp       = Column(DateTime, nullable=False, default=datetime.utcnow)
    coin            = Column(String(10), nullable=False)  # BTC | ETH | SOL | MARKET

    reddit_score    = Column(Float)
    telegram_score  = Column(Float)
    news_score      = Column(Float)
    fear_greed      = Column(Float)
    google_trends   = Column(Float)

    composite       = Column(Float)    # Weighted blend
    velocity        = Column(Float)    # Change vs 2h ago

    post_count      = Column(Integer)  # Reddit posts analysed
    mention_count   = Column(Integer)  # Total mentions across sources

    __table_args__ = (
        Index("ix_sentiment_lookup", "coin", "timestamp"),
    )


class Prediction(Base):
    """Predictive model outputs per signal (phase 2 feature)."""
    __tablename__ = "predictions"

    id              = Column(Integer, primary_key=True)
    signal_id       = Column(Integer, ForeignKey("signals.id"))
    timestamp       = Column(DateTime, default=datetime.utcnow)

    model_version   = Column(String(20))
    win_probability = Column(Float)     # 0.0 – 1.0
    expected_pnl_pct = Column(Float)
    confidence      = Column(Float)

    # Feature vector used (JSON for auditability)
    features_json   = Column(JSON)

    # Was the prediction correct?
    correct         = Column(Boolean)   # Filled when trade closes

    signal          = relationship("Signal", back_populates="prediction")


class DailyStats(Base):
    """Aggregated daily performance — written at end of each day."""
    __tablename__ = "daily_stats"

    id                  = Column(Integer, primary_key=True)
    date                = Column(String(10), nullable=False, unique=True)  # YYYY-MM-DD

    total_signals       = Column(Integer, default=0)
    signals_passed_gate = Column(Integer, default=0)
    signals_acted_on    = Column(Integer, default=0)

    total_trades        = Column(Integer, default=0)
    wins                = Column(Integer, default=0)
    losses              = Column(Integer, default=0)
    win_rate            = Column(Float)

    pnl_usd             = Column(Float, default=0.0)
    pnl_pct             = Column(Float, default=0.0)
    fees_usd            = Column(Float, default=0.0)

    best_trade_pnl_pct  = Column(Float)
    worst_trade_pnl_pct = Column(Float)
    avg_hold_minutes    = Column(Float)

    best_signal_type    = Column(String(20))
    avg_score_winners   = Column(Float)
    avg_score_losers    = Column(Float)

    portfolio_value_usd = Column(Float)
    portfolio_peak_usd  = Column(Float)

    claude_api_cost_usd = Column(Float, default=0.0)
    sim_mode            = Column(Boolean, default=True)
    profile             = Column(String(30))
    strategy            = Column(String(30))


class CircuitBreakerLog(Base):
    """Log every time a circuit breaker fires."""
    __tablename__ = "circuit_breaker_log"

    id          = Column(Integer, primary_key=True)
    timestamp   = Column(DateTime, default=datetime.utcnow)
    reason      = Column(String(50))   # daily_loss | consecutive_loss | drawdown | kill_switch
    detail      = Column(Text)
    auto_resume_at = Column(DateTime)  # When bot will auto-resume (if applicable)
    manually_resolved = Column(Boolean, default=False)
